version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
      MYSQL_INITDB_CHARSET: utf8mb4
      LANG: C.UTF_8
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    command: flask run --host=0.0.0.0
