version: '3'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: users

  web:
    build: .
    ports:
      - "5000:5000"
    environment:
      DB_HOST: db
    depends_on:
      - db
    command: flask run --host=0.0.0.0
