ERROR_DICT = {
    'ACC01': 'Invalid credentials',
    'ACC02': 'Password and repeated password do not match',
    'ACC03': 'Password must be at least 8 characters long and contain at least one uppercase letter, one lowercase '
             'letter, and one digit',
    'ACC04': 'Admin phone number must be exactly 9 digits',
    'ACC05': 'Admin with provided username or email already exists',
    'ACC06': 'An error occurred while registering admin',
    'ACC07': 'Admin not found',
    'ACC08': 'Unauthorized. Please make sure you are logged in as administrator',
    'ACC09': 'User not found',
    'ACC10': 'Forbidden. Only administrators can access this data.',
    'ACC11': 'Forbidden. Only administrators can block users.',
    'ACC12': 'Forbidden. Only administrators can unblock users.',
    'ACC13': 'Permission not found',
    'ACC14': 'Cannot add permission. Admin already has this permission',
    'ACC15': 'An unknown error occurred while adding permission',
    'ACC16': 'Cannot delete permission. Admin does not have this permission',
    'ACC17': 'An error occurred while removing permission',
    'ACC18': 'Permissions initialization failed',
    'ACC19': 'Permissions are not empty',
    'ACC20': 'Administrator with the same username already exists',
    'ACC21': 'Administrator with the same email already exists',
    'ACC22': 'Administrator with the same phone number already exists',
    'ACC23': 'New password not provided',
    'ACC24': 'An error occurred while initializing test users and admins',
    'ACC25': 'Forbidden. Only administrators can access this endpoint',
    'ACC26': 'Email must be sent with not empty message and from valid user account',
    'ACC27': 'Token has expired',
    'ACC28': 'Invalid token',
}
